/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButtons: typeof import('./src/components/ActionButtons.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    DisclaimerModal: typeof import('./src/components/DisclaimerModal.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    HelpTooltip: typeof import('./src/components/HelpTooltip.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    LanguageToggle: typeof import('./src/components/LanguageToggle.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    NotificationContainer: typeof import('./src/components/NotificationContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    ToolCard: typeof import('./src/components/ToolCard.vue')['default']
    ToolHelpContent: typeof import('./src/components/ToolHelpContent.vue')['default']
    ToolSidebar: typeof import('./src/components/ToolSidebar.vue')['default']
  }
}
